### PR TITLE
Feature: Configurable HEAD retry codes

### LINKED ISSUE #114: http://www.diamondproducers.com multiple 200 pages marked as 404
http://www.diamondproducers.com multiple 200 pages marked as 404 .

Is it a bug or an unusual way of blocking crawlers ?

### PR DESCRIPTION
**Pull request by beaulac**
EDIT: The following behavior is not what will be included in v0.8.0, but is still available in branch https://github.com/beaulac/broken-link-checker/tree/old_configurable-head-retry

Adds a new option `headRetryCodes` to specify which HTTP codes should trigger a HEAD to be retried with a GET. This feature is to address issues with strangely behaving servers that respond to HEAD with non-405 error codes, e.g. will fix #114 .

Example usage:
```javascript
{
    headRetryCodes: [404, 500]
}
```
Will retry HEAD with a GET when either a 404 or 500 is encountered.

This maintains backwards compatibility with the `retry405Head` option; if `retry405Head` is true, then 405 is added to headRetryCodes.

### CODE REVIEW

**Comment by beaulac** [comment]
@stevenvachon Please let me know if you'd prefer this PR to target the v0.8.0 branch instead 😃

**Comment by neorganic** [comment]
I've forked the project and reverted to it only to have this PR included in my app, really think this should be pulled in the main project as well!

**Comment by jpowell** [comment]
Should we start a different fork of this if the @stefanSchinkel doesn't want to maintain it any more?

I added header support in #126 and think that would benefit many if you want to check the authenticated experience as we did...

**Comment by stevenvachon** [comment]
* rebase with v0.8.0 branch
* rename `retry405Head` option to `retryHeadFail`, and adjust logic accordingly
* rename `headRetryCodes` to `retryHeadCodes`
* make `retryHeadCodes` default value `[405]` -- should it also include 500? I don't think 404 should be default, at least

**Comment by beaulac** [comment]
Thanks @stevenvachon , I'll follow your change requests :+1:

`404` & `500` were just example usages, the default value is already `[405]` as requested.

**Comment by fxedel** [comment]
@stevenvachon @beaulac Any updates on this?

**Comment by beaulac** [comment]
Finally got around to it 🎉 

options changed: `retry405Head`->`retryHeadFail`,`retryHeadCodes`

New options in 0.8.0:

### `retryHeadFail`
Type: `Boolean`  
Default value: `true`  
Some servers do not respond correctly to a `'head'` request method. When `true`, a link resulting in a status code specified in `retryHeadCodes` option will be re-requested using a `'get'` method before deciding that it is broken. This is only relevant if the `requestMethod` option is set to `'head'`.

### `retryHeadCodes`
Type: `Number[]`  
Default value: `[405]`  
List of status codes that will cause a `'head'` request to be retried with a `'get'`. This is only relevant if `retryHeadFail` option is `true`.

@stevenvachon Please lmk if anything needs to be adjusted 🙏

**Comment by fxedel** [comment]
This feature isn't included in the newest v0.8.0 version. Is that intended? If so, when will it be added?

**Comment by stevenvachon** [comment]
Aye, it got closed automatically when I removed the 0.8 branch. I'd forgotten about this PR. I'll make a note of it to re-implement it.

**Comment by stevenvachon** [comment]
This is now in master branch. v0.8 is still not released as of this comment.

**Pull request closed without merging**
