### PR TITLE
Fix help command

### PR DESCRIPTION
**Pull request by nhoizey**
`-?` doesn't work

### CODE REVIEW

**Comment by stevenvachon** [comment]
Works fine here on Windows and Mac. Which OS are you having difficulty with?

**Comment by nhoizey** [comment]
On my Mac:

```shell
$ blc -?
zsh: no matches found: -?
```

**Comment by stevenvachon** [comment]
You have zsh installed on your Mac? It might be an issue with that as bash works fine here.

It could be zsh's globbing. Does this work in zsh?:
```shell
blc "-?"
```

**Comment by nhoizey** [comment]
It works with quotes!

**Comment by stevenvachon** [comment]
Thanks for pointing this out. We'll go with `--help` as you'd suggested as it's safest for all shells.

**Comment by nhoizey** [comment]
ok, glad I helped find this "issue"

**Pull request merged**
