### PR TITLE
Write logs for broken links to file

### PR DESCRIPTION
**Pull request by FelixZilber**
Get a file with only broken links logs.

### CODE REVIEW

**Comment by rmoriz** [comment]
I like this feature because when running in a CI/monitoring environment a simple, parseable output would be great.

**Comment by felzilber** [comment]
I had few bugs in my implementation. Will get to it next week, and will create a PR

**Comment by FelixZilber** [comment]
@rmoriz check this [PR](https://github.com/stevenvachon/broken-link-checker/pull/113)

**Comment by ydcool** [comment]
It this still in progress? I like this feature too.

**Comment by stevenvachon** [comment]
I won't be merging this or implementing a file system write in this way. At some point, there will be an option to at least output a JSON file.

**Pull request closed without merging**
